ARG BRANCH=master
FROM docker.io/endlessm/eos:${BRANCH}
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gir1.2-gnomedesktop-3.0 \
        gnome-user-guide \
        python3-boto3 \
        python3-gi \
        python3-jinja2 \
        python3-magic \
        yelp-tools \
        && \
    apt-get clean
